export const Routes = {
	ANALYTICS: "/analytics",
	HOME: "/",
	DATA: "/data",
	DETAILS: "/details",
	TABLE: "/table",
	PROVIDERS: "/providers",
	GEAR: "/gear",
	INBODY: "/inbody",
	INBODY_ADD: "/inbody/add",
	INBODY_EDIT: "/inbody/:id/edit",
	ADD: "/add",
	SETTINGS: "/settings",
	DEBUG: "/debug",
};
