export const Routes = {
	ANALYTICS: "/analytics",
	CALENDAR: "/calendar",
	HOME: "/",
	DATA: "/data",
	DETAILS: "/details",
	TABLE: "/table",
	PROVIDERS: "/providers",
	STRAVA: "/providers/strava",
	STRAVA_WEBHOOKS: "/providers/strava/webhooks",
	PROVIDER_DETAILS: "/providers/:provider",
	PROVIDER_ACTIVITY_SYNC: "/providers/:provider/activity-sync",
	GEAR: "/gear",
	GEAR_ADD: "/gear/add",
	INBODY: "/inbody",
	INBODY_ADD: "/inbody/add",
	INBODY_EDIT: "/inbody/:id/edit",
	INBODY_HISTORY: "/inbody/history",
	ADD: "/add",
	SYNC: "/sync",
	SETTINGS: "/settings",
	DEBUG: "/debug",
};
