CREATE TABLE `inbody` (
	`id` text PRIMARY KEY NOT NULL,
	`weight` integer NOT NULL,
	`muscle_mass` integer NOT NULL,
	`body_fat_mass` integer NOT NULL,
	`bmi` integer NOT NULL,
	`percentage_body_fat` integer NOT NULL,
	`lean_core` integer,
	`lean_left_arm` integer,
	`lean_right_arm` integer,
	`lean_left_leg` integer,
	`lean_right_leg` integer,
	`fat_core` integer,
	`fat_left_arm` integer,
	`fat_right_arm` integer,
	`fat_left_leg` integer,
	`fat_right_leg` integer,
	`composition_body_water` integer,
	`composition_protein` integer,
	`composition_minerals` integer,
	`composition_body_fat` integer,
	`type` text NOT NULL,
	`date` text NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
